### 2880. Select Data

DataFrame students
+-------------+--------+
| Column Name | Type   |
+-------------+--------+
| student_id  | int    |
| name        | object |
| age         | int    |
+-------------+--------+

Write a solution to select the name and age of the student with student_id = 101.

The result format is in the following example.

 

Example 1:
Input:
+------------+---------+-----+
| student_id | name    | age |
+------------+---------+-----+
| 101        | Ulysses | 13  |
| 53         | William | 10  |
| 128        | Henry   | 6   |
| 3          | Henry   | 11  |
+------------+---------+-----+
Output:
+---------+-----+
| name    | age | 
+---------+-----+
| Ulysses | 13  |
+---------+-----+
Explanation:
Student Ulysses has student_id = 101, we select the name and age.

In [7]:
import pandas as pd

data = {
    "student_id": [101,53,128,3],
    "name": ["Ulysses", "William", "Henry", "Henry"],
    "age": [13, 10, 6, 11]
}
students = pd.DataFrame(data)

students

   student_id     name  age
0         101  Ulysses   13
1          53  William   10
2         128    Henry    6
3           3    Henry   11

In [16]:
students.loc[students["student_id"] == 101, ["name", "age"]]

      name  age
0  Ulysses   13